'use strict';
(()=>{
const cfg=window.ELITE_SUPABASE||{};
const API=String(cfg.url||'').replace(/\/$/,'')+'/rest/v1/products';
const key=cfg.publishableKey||'';
const $=s=>document.querySelector(s);
const grid=$('#productGrid'),q=$('#q'),count=$('#count'),empty=$('#empty'),more=$('#more');
const priceFilter=$('#priceFilter'),brandFilter=$('#brandFilter'),noteFilter=$('#noteFilter'),availabilityFilter=$('#availabilityFilter');
const suggestions=$('#suggestions'),favoritesOnly=$('#favoritesOnly'),favoritesSummary=$('#favoritesSummary');
function readPreRendered(){try{const el=document.getElementById('preRenderedProducts');const value=JSON.parse(el?.textContent||'[]');return Array.isArray(value)?value:[]}catch{return []}}
let products=readPreRendered(),gender='todos',visible=24,onlyFavorites=false,suggestionIndex=-1;
const preRenderedById=new Map(products.map(product=>[Number(product.id),product]));
const FAVORITES_KEY='elite-scents-favorites-v1';
const CART_KEY='elite-scents-cart-v1';
const THEME_KEY='elite-scents-theme-v1';
const USD_RATE_DOP=63;
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const genderLabel={hombre:'Hombre',mujer:'Mujer',unisex:'Unisex'};
const statusLabel={disponible:'Disponible',agotado:'Agotado',encargo:'Solo por encargo'};
const availabilitySchema={disponible:'https://schema.org/InStock',agotado:'https://schema.org/OutOfStock',encargo:'https://schema.org/PreOrder'};
function readFavorites(){try{const value=JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]');return new Set(Array.isArray(value)?value.map(Number).filter(Number.isFinite):[])}catch{return new Set()}}
let favoriteIds=readFavorites();
function saveFavorites(){try{localStorage.setItem(FAVORITES_KEY,JSON.stringify([...favoriteIds]))}catch{}updateFavoriteSummary()}
function readCart(){try{const value=JSON.parse(localStorage.getItem(CART_KEY)||'[]');return Array.isArray(value)?value:[]}catch{return []}}
function saveCart(value){try{localStorage.setItem(CART_KEY,JSON.stringify(value))}catch{}updateCartCount()}
function updateCartCount(){const items=readCart(),qty=items.reduce((sum,item)=>sum+(Number(item.qty)||1),0),el=$('#cartCount'),nav=$('#cartNav');if(el)el.textContent=qty;if(nav)nav.classList.toggle('has-items',qty>0)}
function firstSize(value){return String(value||'').split('/')[0].trim()}
function chooseVariant(p){
  const prices=numbers(p.price),sizes=String(p.size||'').split('/').map(v=>v.trim()).filter(Boolean);
  if(prices.length<=1)return {unit_price:prices[0]||0,size:p.size||''};
  const options=prices.map((price,i)=>(i+1)+'. '+(sizes[i]||sizes[0]||'Presentación')+' — RD
function updateFavoriteSummary(){const n=favoriteIds.size;favoritesSummary.textContent=n?n+' '+(n===1?'perfume guardado':'perfumes guardados')+' en este dispositivo.':'Pulsa el corazón de cualquier perfume para guardarlo en este dispositivo.'}
function numbers(value){return (String(value).match(/[0-9][0-9,.]*/g)||[]).map(v=>Number(v.replace(/[,.]/g,''))).filter(Number.isFinite)}
function maxPrice(p){const values=numbers(p.price);return values.length?Math.max(...values):0}
function usdPrice(p){const value=maxPrice(p);return value?'US$'+Math.round(value/USD_RATE_DOP)+' aprox.':''}
function preferredTheme(){try{const value=localStorage.getItem(THEME_KEY);return ['light','dark','system'].includes(value)?value:'system'}catch{return 'system'}}
function applyTheme(value){const mode=['light','dark','system'].includes(value)?value:'system';if(mode==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=mode;const control=$('#themeMode');if(control)control.value=mode;try{localStorage.setItem(THEME_KEY,mode)}catch{}}
function allNotes(p){return [...(p.notes_top||[]),...(p.notes_heart||[]),...(p.notes_base||[])]}
function whatsapp(p){const status=p.availability==='agotado'?'está agotado; quisiera saber cuándo vuelve':p.availability==='encargo'?'es por encargo; quisiera solicitarlo':'me interesa';return 'https://wa.me/18094333348?text='+encodeURIComponent('Hola Elite Scents RD, '+status+': '+p.name+' ('+p.size+', '+p.price+'). ¿Puedes ayudarme?')}
function catalogueVisual(p,className='photo'){const wrap=document.createElement('div');wrap.className=className;wrap.setAttribute('role','img');wrap.setAttribute('aria-label','Frasco de '+p.name+(p.brand?' de '+p.brand:''));
if(p.image_url&&/^https:\/\//i.test(p.image_url)){wrap.classList.add('custom');wrap.style.backgroundImage='url('+JSON.stringify(p.image_url)+')';wrap.style.backgroundSize='contain';wrap.style.backgroundPosition='center';return wrap}
const page=Number(p.page),slot=Number(p.slot);
if(Number.isInteger(page)&&page>=1&&page<=36&&Number.isInteger(slot)&&slot>=0&&slot<12){wrap.style.backgroundImage='url("/pages/page-'+String(page).padStart(2,'0')+'.webp")';wrap.style.backgroundPosition=(slot%3*50)+'% '+(Math.floor(slot/3)*30.13).toFixed(2)+'%'}
return wrap}
function favoriteButton(p){const button=document.createElement('button');button.type='button';button.className='favorite-button';const selected=favoriteIds.has(Number(p.id));button.textContent=selected?'♥':'♡';button.setAttribute('aria-label',(selected?'Quitar ':'Agregar ')+p.name+(selected?' de favoritos':' a favoritos'));button.setAttribute('aria-pressed',String(selected));button.addEventListener('click',e=>{e.stopPropagation();const id=Number(p.id);favoriteIds.has(id)?favoriteIds.delete(id):favoriteIds.add(id);saveFavorites();render()});return button}
function card(p){const item=document.createElement('article');item.className='perfume';item.id='producto-'+p.id;item.dataset.productId=p.id;const visual=catalogueVisual(p);visual.append(favoriteButton(p));const status=p.availability in statusLabel?p.availability:'disponible';const badge=document.createElement('span');badge.className='stock stock-'+status;badge.textContent=statusLabel[status];const meta=document.createElement('div');meta.className='meta';const brand=document.createElement('span');brand.textContent=p.brand||genderLabel[p.gender]||'Perfume';const volume=document.createElement('span');volume.textContent=p.size||'';meta.append(brand,volume);const title=document.createElement('h3');title.textContent=p.name;const note=document.createElement('div');note.className='size';note.textContent=allNotes(p).slice(0,3).join(' · ')||(genderLabel[p.gender]||'Unisex');const price=document.createElement('div');price.className='price';const dop=document.createElement('strong');dop.textContent=p.price||'Precio a confirmar';const usd=document.createElement('small');usd.textContent=usdPrice(p);price.append(dop,usd);const actions=document.createElement('div');actions.className='card-actions';const detail=document.createElement('button');detail.type='button';detail.textContent='Ver detalles';detail.addEventListener('click',()=>openProduct(p));const add=document.createElement('button');add.type='button';add.dataset.addCart=String(p.id);add.textContent=status==='agotado'?'Agotado':'Agregar al carrito';add.disabled=status==='agotado';add.addEventListener('click',()=>addToCart(p));actions.append(detail,add);item.append(visual,badge,meta,title,note,price,actions);return item}
function priceMatches(p,value){const n=maxPrice(p);if(value==='under3000')return n<3000;if(value==='3000-4999')return n>=3000&&n<5000;if(value==='5000-6999')return n>=5000&&n<7000;if(value==='7000plus')return n>=7000;return true}
function matches(){const term=norm(q.value.trim()),brand=brandFilter.value,note=noteFilter.value,status=availabilityFilter.value;return products.filter(p=>{
const searchable=norm([p.name,p.brand,p.size,p.price,...allNotes(p)].join(' '));
return (!term||searchable.includes(term))&&(gender==='todos'||p.gender===gender)&&(brand==='all'||p.brand===brand)&&(note==='all'||allNotes(p).includes(note))&&(status==='all'||p.availability===status)&&priceMatches(p,priceFilter.value)&&(!onlyFavorites||favoriteIds.has(Number(p.id)))
})}
function render(){const result=matches(),fragment=document.createDocumentFragment();result.slice(0,visible).forEach(p=>fragment.append(card(p)));grid.replaceChildren(fragment);count.textContent=result.length+' '+(result.length===1?'fragancia':'fragancias');empty.hidden=result.length!==0;more.hidden=result.length<=visible;favoritesOnly.classList.toggle('active',onlyFavorites);favoritesOnly.textContent=onlyFavorites?'♥ Mis favoritos':'♡ Mis favoritos'}
function unique(values){return [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es',{sensitivity:'base'}))}
function option(value,label=value){const o=document.createElement('option');o.value=value;o.textContent=label;return o}
function prepareFilters(){brandFilter.replaceChildren(brandFilter.options[0]);noteFilter.replaceChildren(noteFilter.options[0]);unique(products.map(p=>p.brand)).forEach(v=>brandFilter.append(option(v)));unique(products.flatMap(allNotes)).forEach(v=>noteFilter.append(option(v)))}
function showSuggestions(){const term=norm(q.value.trim());if(term.length<2){closeSuggestions();return}const found=products.filter(p=>norm(p.name+' '+p.brand).includes(term)).slice(0,7);suggestions.replaceChildren();found.forEach((p,i)=>{const li=document.createElement('li');li.role='option';li.id='suggestion-'+i;li.textContent=p.name+(p.brand?' · '+p.brand:'');li.addEventListener('mousedown',e=>{e.preventDefault();chooseSuggestion(p.name)});suggestions.append(li)});suggestions.hidden=!found.length;q.setAttribute('aria-expanded',String(!!found.length));suggestionIndex=-1}
function closeSuggestions(){suggestions.hidden=true;suggestions.replaceChildren();q.setAttribute('aria-expanded','false');q.removeAttribute('aria-activedescendant');suggestionIndex=-1}
function chooseSuggestion(name){q.value=name;closeSuggestions();visible=24;render();$('#coleccion').scrollIntoView()}
function moveSuggestion(direction){const items=[...suggestions.children];if(!items.length)return;suggestionIndex=(suggestionIndex+direction+items.length)%items.length;items.forEach((el,i)=>el.classList.toggle('selected',i===suggestionIndex));q.setAttribute('aria-activedescendant',items[suggestionIndex].id)}
function fillText(id,values){$(id).textContent=values?.length?values.join(', '):'Información pendiente'}
function galleryUrls(p){return unique([p.image_url,...(p.gallery_urls||[])]).filter(v=>/^https:\/\//i.test(v)).slice(0,3)}
function openProduct(p){const dialog=$('#productDialog'),main=$('#dialogMainImage'),gallery=$('#dialogGallery');$('#dialogBrand').textContent=p.brand||'Elite Scents RD';$('#dialogTitle').textContent=p.name;$('#dialogPrice').textContent=p.price||'Precio a confirmar';$('#dialogPriceUsd').textContent=usdPrice(p);$('#dialogSize').textContent=p.size||'Por confirmar';$('#dialogStatus').className='stock stock-'+p.availability;$('#dialogStatus').textContent=statusLabel[p.availability]||'Disponible';$('#dialogDescription').textContent=p.description||'Consulta por WhatsApp la disponibilidad, presentación y detalles de esta fragancia.';fillText('#dialogTop',p.notes_top);fillText('#dialogHeart',p.notes_heart);fillText('#dialogBase',p.notes_base);const wa=$('#dialogWhatsapp');wa.href=whatsapp(p);const add=$('#dialogAddCart');if(add){add.disabled=p.availability==='agotado';add.textContent=p.availability==='agotado'?'Agotado':'Agregar al carrito';add.onclick=()=>addToCart(p)}gallery.replaceChildren();main.replaceChildren();const urls=galleryUrls(p);if(urls.length){const image=document.createElement('img');image.src=urls[0];image.alt='Frasco de '+p.name;image.loading='eager';main.append(image);urls.forEach((url,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label','Ver imagen '+(i+1)+' de '+p.name);const img=document.createElement('img');img.src=url;img.alt='Vista '+(i+1)+' del perfume '+p.name;img.loading='lazy';b.append(img);b.addEventListener('click',()=>{image.src=url;image.alt='Vista '+(i+1)+' del perfume '+p.name});gallery.append(b)})}else main.append(catalogueVisual(p,'dialog-catalogue-image'));dialog.showModal()}
function resetFilters(){q.value='';gender='todos';onlyFavorites=false;priceFilter.value=brandFilter.value=noteFilter.value=availabilityFilter.value='all';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='todos'));visible=24;closeSuggestions();render()}
function unavailable(){products=[];render();grid.setAttribute('aria-busy','false');empty.hidden=false;empty.textContent='El catálogo no está disponible ahora. Escríbenos por WhatsApp para consultar un perfume.';count.textContent='Catálogo no disponible'}
function catalogMessage(message){const el=$('#catalogStatus');if(el)el.textContent=message}
async function load(){if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(String(cfg.url||'').replace(/\/$/,''))||!key){unavailable();return}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const fields='id,name,price,size,gender,page,slot,image_url,sort_order,availability,brand,notes_top,notes_heart,notes_base,gallery_urls,description';const response=await fetch(API+'?select='+encodeURIComponent(fields)+'&active=eq.true&order=sort_order.asc,id.asc&limit=1000',{headers:{apikey:key},signal:controller.signal});if(!response.ok)throw new Error('HTTP '+response.status);const fresh=await response.json();if(!Array.isArray(fresh)||!fresh.length)throw new Error('Catálogo vacío');products=fresh.map(product=>{const saved=preRenderedById.get(Number(product.id));return saved?{...product,notes_top:product.notes_top?.length?product.notes_top:saved.notes_top,notes_heart:product.notes_heart?.length?product.notes_heart:saved.notes_heart,notes_base:product.notes_base?.length?product.notes_base:saved.notes_base}:product});prepareFilters();render();updateFavoriteSummary();grid.setAttribute('aria-busy','false');catalogMessage('')}catch{if(products.length){render();grid.setAttribute('aria-busy','false');catalogMessage('Mostrando la última versión guardada del catálogo. Puedes consultar disponibilidad por WhatsApp.')}else unavailable()}finally{clearTimeout(timer)}}
q.addEventListener('input',()=>{visible=24;showSuggestions();render()});q.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();moveSuggestion(1)}else if(e.key==='ArrowUp'){e.preventDefault();moveSuggestion(-1)}else if(e.key==='Enter'&&suggestionIndex>=0){e.preventDefault();chooseSuggestion(suggestions.children[suggestionIndex].textContent.split(' · ')[0])}else if(e.key==='Escape')closeSuggestions()});q.addEventListener('blur',()=>setTimeout(closeSuggestions,120));
[priceFilter,brandFilter,noteFilter,availabilityFilter].forEach(el=>el.addEventListener('change',()=>{visible=24;render()}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));button.classList.add('active');gender=button.dataset.filter;visible=24;render()}));
favoritesOnly.addEventListener('click',()=>{onlyFavorites=!onlyFavorites;visible=24;render()});$('#showFavorites').addEventListener('click',()=>{onlyFavorites=true;visible=24;render();$('#coleccion').scrollIntoView()});$('#clearFilters').addEventListener('click',resetFilters);more.addEventListener('click',()=>{visible+=24;render()});$('#dialogClose').addEventListener('click',()=>$('#productDialog').close());$('#productDialog').addEventListener('click',e=>{if(e.target===$('#productDialog'))$('#productDialog').close()});applyTheme(preferredTheme());$('#themeMode')?.addEventListener('change',e=>applyTheme(e.target.value));$('#year').textContent=new Date().getFullYear();updateCartCount();if(products.length){prepareFilters();render();updateFavoriteSummary();grid.setAttribute('aria-busy','false')}load()
})();
+new Intl.NumberFormat('es-DO').format(price));
  const answer=prompt('Elige la presentación de '+p.name+':\n'+options.join('\n'),'1');
  if(answer===null)return null;
  const index=Math.max(0,Math.min(prices.length-1,(Number(answer)||1)-1));
  return {unit_price:prices[index],size:sizes[index]||sizes[0]||p.size||''};
}
function showCartToast(message){document.querySelector('.cart-toast')?.remove();const el=document.createElement('div');el.className='cart-toast';el.textContent=message;document.body.append(el);setTimeout(()=>el.remove(),2400)}
function addToCart(p){
  if(p.availability==='agotado'){showCartToast('Este perfume está agotado.');return}
  const variant=chooseVariant(p);if(!variant||!variant.unit_price)return;
  const cart=readCart(),key=[p.id,variant.unit_price,variant.size].join(':');
  const existing=cart.find(item=>String(item.key)===key);
  if(existing)existing.qty=Math.min(10,(Number(existing.qty)||1)+1);
  else cart.push({key,product_id:Number(p.id),name:p.name,brand:p.brand||'',price:p.price,size:variant.size,unit_price:variant.unit_price,qty:1});
  saveCart(cart);showCartToast(p.name+' agregado al carrito.');
}
function updateFavoriteSummary(){const n=favoriteIds.size;favoritesSummary.textContent=n?n+' '+(n===1?'perfume guardado':'perfumes guardados')+' en este dispositivo.':'Pulsa el corazón de cualquier perfume para guardarlo en este dispositivo.'}
function numbers(value){return (String(value).match(/[0-9][0-9,.]*/g)||[]).map(v=>Number(v.replace(/[,.]/g,''))).filter(Number.isFinite)}
function maxPrice(p){const values=numbers(p.price);return values.length?Math.max(...values):0}
function usdPrice(p){const value=maxPrice(p);return value?'US$'+Math.round(value/USD_RATE_DOP)+' aprox.':''}
function preferredTheme(){try{const value=localStorage.getItem(THEME_KEY);return ['light','dark','system'].includes(value)?value:'system'}catch{return 'system'}}
function applyTheme(value){const mode=['light','dark','system'].includes(value)?value:'system';if(mode==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=mode;const control=$('#themeMode');if(control)control.value=mode;try{localStorage.setItem(THEME_KEY,mode)}catch{}}
function allNotes(p){return [...(p.notes_top||[]),...(p.notes_heart||[]),...(p.notes_base||[])]}
function whatsapp(p){const status=p.availability==='agotado'?'está agotado; quisiera saber cuándo vuelve':p.availability==='encargo'?'es por encargo; quisiera solicitarlo':'me interesa';return 'https://wa.me/18094333348?text='+encodeURIComponent('Hola Elite Scents RD, '+status+': '+p.name+' ('+p.size+', '+p.price+'). ¿Puedes ayudarme?')}
function catalogueVisual(p,className='photo'){const wrap=document.createElement('div');wrap.className=className;wrap.setAttribute('role','img');wrap.setAttribute('aria-label','Frasco de '+p.name+(p.brand?' de '+p.brand:''));
if(p.image_url&&/^https:\/\//i.test(p.image_url)){wrap.classList.add('custom');wrap.style.backgroundImage='url('+JSON.stringify(p.image_url)+')';wrap.style.backgroundSize='contain';wrap.style.backgroundPosition='center';return wrap}
const page=Number(p.page),slot=Number(p.slot);
if(Number.isInteger(page)&&page>=1&&page<=36&&Number.isInteger(slot)&&slot>=0&&slot<12){wrap.style.backgroundImage='url("/pages/page-'+String(page).padStart(2,'0')+'.webp")';wrap.style.backgroundPosition=(slot%3*50)+'% '+(Math.floor(slot/3)*30.13).toFixed(2)+'%'}
return wrap}
function favoriteButton(p){const button=document.createElement('button');button.type='button';button.className='favorite-button';const selected=favoriteIds.has(Number(p.id));button.textContent=selected?'♥':'♡';button.setAttribute('aria-label',(selected?'Quitar ':'Agregar ')+p.name+(selected?' de favoritos':' a favoritos'));button.setAttribute('aria-pressed',String(selected));button.addEventListener('click',e=>{e.stopPropagation();const id=Number(p.id);favoriteIds.has(id)?favoriteIds.delete(id):favoriteIds.add(id);saveFavorites();render()});return button}
function card(p){const item=document.createElement('article');item.className='perfume';item.id='producto-'+p.id;item.dataset.productId=p.id;const visual=catalogueVisual(p);visual.append(favoriteButton(p));const status=p.availability in statusLabel?p.availability:'disponible';const badge=document.createElement('span');badge.className='stock stock-'+status;badge.textContent=statusLabel[status];const meta=document.createElement('div');meta.className='meta';const brand=document.createElement('span');brand.textContent=p.brand||genderLabel[p.gender]||'Perfume';const volume=document.createElement('span');volume.textContent=p.size||'';meta.append(brand,volume);const title=document.createElement('h3');title.textContent=p.name;const note=document.createElement('div');note.className='size';note.textContent=allNotes(p).slice(0,3).join(' · ')||(genderLabel[p.gender]||'Unisex');const price=document.createElement('div');price.className='price';const dop=document.createElement('strong');dop.textContent=p.price||'Precio a confirmar';const usd=document.createElement('small');usd.textContent=usdPrice(p);price.append(dop,usd);const actions=document.createElement('div');actions.className='card-actions';const detail=document.createElement('button');detail.type='button';detail.textContent='Ver detalles';detail.addEventListener('click',()=>openProduct(p));const wa=document.createElement('a');wa.href=whatsapp(p);wa.target='_blank';wa.rel='noopener noreferrer';wa.textContent=status==='agotado'?'Consultar reposición ↗':status==='encargo'?'Solicitar por encargo ↗':'WhatsApp ↗';actions.append(detail,wa);item.append(visual,badge,meta,title,note,price,actions);return item}
function priceMatches(p,value){const n=maxPrice(p);if(value==='under3000')return n<3000;if(value==='3000-4999')return n>=3000&&n<5000;if(value==='5000-6999')return n>=5000&&n<7000;if(value==='7000plus')return n>=7000;return true}
function matches(){const term=norm(q.value.trim()),brand=brandFilter.value,note=noteFilter.value,status=availabilityFilter.value;return products.filter(p=>{
const searchable=norm([p.name,p.brand,p.size,p.price,...allNotes(p)].join(' '));
return (!term||searchable.includes(term))&&(gender==='todos'||p.gender===gender)&&(brand==='all'||p.brand===brand)&&(note==='all'||allNotes(p).includes(note))&&(status==='all'||p.availability===status)&&priceMatches(p,priceFilter.value)&&(!onlyFavorites||favoriteIds.has(Number(p.id)))
})}
function render(){const result=matches(),fragment=document.createDocumentFragment();result.slice(0,visible).forEach(p=>fragment.append(card(p)));grid.replaceChildren(fragment);count.textContent=result.length+' '+(result.length===1?'fragancia':'fragancias');empty.hidden=result.length!==0;more.hidden=result.length<=visible;favoritesOnly.classList.toggle('active',onlyFavorites);favoritesOnly.textContent=onlyFavorites?'♥ Mis favoritos':'♡ Mis favoritos'}
function unique(values){return [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es',{sensitivity:'base'}))}
function option(value,label=value){const o=document.createElement('option');o.value=value;o.textContent=label;return o}
function prepareFilters(){brandFilter.replaceChildren(brandFilter.options[0]);noteFilter.replaceChildren(noteFilter.options[0]);unique(products.map(p=>p.brand)).forEach(v=>brandFilter.append(option(v)));unique(products.flatMap(allNotes)).forEach(v=>noteFilter.append(option(v)))}
function showSuggestions(){const term=norm(q.value.trim());if(term.length<2){closeSuggestions();return}const found=products.filter(p=>norm(p.name+' '+p.brand).includes(term)).slice(0,7);suggestions.replaceChildren();found.forEach((p,i)=>{const li=document.createElement('li');li.role='option';li.id='suggestion-'+i;li.textContent=p.name+(p.brand?' · '+p.brand:'');li.addEventListener('mousedown',e=>{e.preventDefault();chooseSuggestion(p.name)});suggestions.append(li)});suggestions.hidden=!found.length;q.setAttribute('aria-expanded',String(!!found.length));suggestionIndex=-1}
function closeSuggestions(){suggestions.hidden=true;suggestions.replaceChildren();q.setAttribute('aria-expanded','false');q.removeAttribute('aria-activedescendant');suggestionIndex=-1}
function chooseSuggestion(name){q.value=name;closeSuggestions();visible=24;render();$('#coleccion').scrollIntoView()}
function moveSuggestion(direction){const items=[...suggestions.children];if(!items.length)return;suggestionIndex=(suggestionIndex+direction+items.length)%items.length;items.forEach((el,i)=>el.classList.toggle('selected',i===suggestionIndex));q.setAttribute('aria-activedescendant',items[suggestionIndex].id)}
function fillText(id,values){$(id).textContent=values?.length?values.join(', '):'Información pendiente'}
function galleryUrls(p){return unique([p.image_url,...(p.gallery_urls||[])]).filter(v=>/^https:\/\//i.test(v)).slice(0,3)}
function openProduct(p){const dialog=$('#productDialog'),main=$('#dialogMainImage'),gallery=$('#dialogGallery');$('#dialogBrand').textContent=p.brand||'Elite Scents RD';$('#dialogTitle').textContent=p.name;$('#dialogPrice').textContent=p.price||'Precio a confirmar';$('#dialogPriceUsd').textContent=usdPrice(p);$('#dialogSize').textContent=p.size||'Por confirmar';$('#dialogStatus').className='stock stock-'+p.availability;$('#dialogStatus').textContent=statusLabel[p.availability]||'Disponible';$('#dialogDescription').textContent=p.description||'Consulta por WhatsApp la disponibilidad, presentación y detalles de esta fragancia.';fillText('#dialogTop',p.notes_top);fillText('#dialogHeart',p.notes_heart);fillText('#dialogBase',p.notes_base);const wa=$('#dialogWhatsapp');wa.href=whatsapp(p);gallery.replaceChildren();main.replaceChildren();const urls=galleryUrls(p);if(urls.length){const image=document.createElement('img');image.src=urls[0];image.alt='Frasco de '+p.name;image.loading='eager';main.append(image);urls.forEach((url,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label','Ver imagen '+(i+1)+' de '+p.name);const img=document.createElement('img');img.src=url;img.alt='Vista '+(i+1)+' del perfume '+p.name;img.loading='lazy';b.append(img);b.addEventListener('click',()=>{image.src=url;image.alt='Vista '+(i+1)+' del perfume '+p.name});gallery.append(b)})}else main.append(catalogueVisual(p,'dialog-catalogue-image'));dialog.showModal()}
function resetFilters(){q.value='';gender='todos';onlyFavorites=false;priceFilter.value=brandFilter.value=noteFilter.value=availabilityFilter.value='all';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='todos'));visible=24;closeSuggestions();render()}
function unavailable(){products=[];render();grid.setAttribute('aria-busy','false');empty.hidden=false;empty.textContent='El catálogo no está disponible ahora. Escríbenos por WhatsApp para consultar un perfume.';count.textContent='Catálogo no disponible'}
function catalogMessage(message){const el=$('#catalogStatus');if(el)el.textContent=message}
async function load(){if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(String(cfg.url||'').replace(/\/$/,''))||!key){unavailable();return}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const fields='id,name,price,size,gender,page,slot,image_url,sort_order,availability,brand,notes_top,notes_heart,notes_base,gallery_urls,description';const response=await fetch(API+'?select='+encodeURIComponent(fields)+'&active=eq.true&order=sort_order.asc,id.asc&limit=1000',{headers:{apikey:key},signal:controller.signal});if(!response.ok)throw new Error('HTTP '+response.status);const fresh=await response.json();if(!Array.isArray(fresh)||!fresh.length)throw new Error('Catálogo vacío');products=fresh.map(product=>{const saved=preRenderedById.get(Number(product.id));return saved?{...product,notes_top:product.notes_top?.length?product.notes_top:saved.notes_top,notes_heart:product.notes_heart?.length?product.notes_heart:saved.notes_heart,notes_base:product.notes_base?.length?product.notes_base:saved.notes_base}:product});prepareFilters();render();updateFavoriteSummary();grid.setAttribute('aria-busy','false');catalogMessage('')}catch{if(products.length){render();grid.setAttribute('aria-busy','false');catalogMessage('Mostrando la última versión guardada del catálogo. Puedes consultar disponibilidad por WhatsApp.')}else unavailable()}finally{clearTimeout(timer)}}
q.addEventListener('input',()=>{visible=24;showSuggestions();render()});q.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();moveSuggestion(1)}else if(e.key==='ArrowUp'){e.preventDefault();moveSuggestion(-1)}else if(e.key==='Enter'&&suggestionIndex>=0){e.preventDefault();chooseSuggestion(suggestions.children[suggestionIndex].textContent.split(' · ')[0])}else if(e.key==='Escape')closeSuggestions()});q.addEventListener('blur',()=>setTimeout(closeSuggestions,120));
[priceFilter,brandFilter,noteFilter,availabilityFilter].forEach(el=>el.addEventListener('change',()=>{visible=24;render()}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));button.classList.add('active');gender=button.dataset.filter;visible=24;render()}));
favoritesOnly.addEventListener('click',()=>{onlyFavorites=!onlyFavorites;visible=24;render()});$('#showFavorites').addEventListener('click',()=>{onlyFavorites=true;visible=24;render();$('#coleccion').scrollIntoView()});$('#clearFilters').addEventListener('click',resetFilters);more.addEventListener('click',()=>{visible+=24;render()});$('#dialogClose').addEventListener('click',()=>$('#productDialog').close());$('#productDialog').addEventListener('click',e=>{if(e.target===$('#productDialog'))$('#productDialog').close()});applyTheme(preferredTheme());$('#themeMode')?.addEventListener('change',e=>applyTheme(e.target.value));$('#year').textContent=new Date().getFullYear();if(products.length){prepareFilters();render();updateFavoriteSummary();grid.setAttribute('aria-busy','false')}load()
})();
