'use strict';
(()=>{
const cfg=window.ELITE_SUPABASE||{};
const API=String(cfg.url||'').replace(/\/$/,'')+'/rest/v1/products';
const key=cfg.publishableKey||'';
const $=s=>document.querySelector(s);
const grid=$('#productGrid'),q=$('#q'),count=$('#count'),empty=$('#empty'),more=$('#more');
const priceFilter=$('#priceFilter'),brandFilter=$('#brandFilter'),noteFilter=$('#noteFilter'),availabilityFilter=$('#availabilityFilter'),specialFilter=$('#specialFilter');
const suggestions=$('#suggestions'),favoritesOnly=$('#favoritesOnly'),favoritesSummary=$('#favoritesSummary');
// El catálogo completo está en /perfumes.json (la portada lo pide desde el <head>); la portada ya trae listas las primeras
// tarjetas y las secciones destacadas, y de la base de datos solo se piden precio, disponibilidad y ofertas al día.
function catalogSource(){try{const v=JSON.parse(document.getElementById('catalogInfo')?.textContent||'{}');return /^\/perfumes\.json(\?v=[a-f0-9]+)?$/.test(v.src||'')?v.src:''}catch{return ''}}
let products=[],gender='todos',visible=24,onlyFavorites=false,suggestionIndex=-1;
// Secciones de la portada: la publicación guarda los números de «Lo más vendido» y «Nuevos»; «En oferta» sale del catálogo al día.
function readHomeSections(){try{const v=JSON.parse(document.getElementById('homeSections')?.textContent||'{}');const ids=x=>Array.isArray(x)?x.map(Number).filter(Number.isFinite):[];return {vendidos:ids(v.vendidos),nuevos:ids(v.nuevos)}}catch{return {vendidos:[],nuevos:[]}}}
const homeSections=readHomeSections();
let preRenderedById=new Map();
const FAVORITES_KEY='elite-scents-favorites-v1';
const CART_KEY='elite-scents-cart-v3';
const THEME_KEY='elite-scents-theme-v1';
const USD_RATE_DOP=63;
const norm=v=>String(v||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
const genderLabel={hombre:'Hombre',mujer:'Mujer',unisex:'Unisex'};
const statusLabel={disponible:'Disponible',agotado:'Agotado',encargo:'Solo por encargo'};
const availabilitySchema={disponible:'https://schema.org/InStock',agotado:'https://schema.org/OutOfStock',encargo:'https://schema.org/PreOrder'};
function readFavorites(){try{const value=JSON.parse(localStorage.getItem(FAVORITES_KEY)||'[]');return new Set(Array.isArray(value)?value.map(Number).filter(Number.isFinite):[])}catch{return new Set()}}
let favoriteIds=readFavorites();
function saveFavorites(){try{localStorage.setItem(FAVORITES_KEY,JSON.stringify([...favoriteIds]))}catch{}updateFavoriteSummary()}
function readCart(){try{const v=JSON.parse(localStorage.getItem(CART_KEY)||'[]');return Array.isArray(v)?v:[]}catch{return []}}
function saveCart(v){try{localStorage.setItem(CART_KEY,JSON.stringify(v))}catch{}updateCartCount()}
function updateCartCount(){const el=$('#cartCount');if(el)el.textContent=readCart().reduce((n,x)=>n+(Number(x.qty)||1),0)}
function addToCart(p){
 const prices=numbers(p.price);if(!prices.length)return;
 const sizes=String(p.size||'').split('/').map(x=>x.trim()).filter(Boolean);let idx=0;
 if(prices.length>1){
  const options=prices.map((v,i)=>(i+1)+'. '+(sizes[i]||sizes[0]||'Presentación')+' - RD$'+v.toLocaleString('es-DO')).join(String.fromCharCode(10));
  const choice=prompt('Elige presentación:'+String.fromCharCode(10)+options,'1');if(choice===null)return;
  idx=Math.max(0,Math.min(prices.length-1,(Number(choice)||1)-1));
 }
 const unit=prices[idx],size=sizes[idx]||sizes[0]||p.size||'',key=[p.id,unit,size].join(':'),cart=readCart(),found=cart.find(x=>x.key===key);
 if(found)found.qty=Math.min(10,(Number(found.qty)||1)+1);else cart.push({key,product_id:Number(p.id),name:p.name,brand:p.brand||'',price:p.price,size,unit_price:unit,qty:1});
 saveCart(cart);window.EliteStats?.track('carrito',{product_id:p.id});
 document.querySelector('.cart-toast')?.remove();const toast=document.createElement('div');toast.className='cart-toast';toast.textContent=p.name+' agregado al carrito';document.body.append(toast);setTimeout(()=>toast.remove(),1800);
}
function updateFavoriteSummary(){if(!favoritesSummary)return;const n=favoriteIds.size;favoritesSummary.textContent=n?n+' '+(n===1?'perfume guardado':'perfumes guardados')+' en este dispositivo.':'Pulsa el corazón de cualquier perfume para guardarlo en este dispositivo.'}
function numbers(value){return (String(value).match(/[0-9][0-9,.]*/g)||[]).map(v=>Number(v.replace(/[,.]/g,''))).filter(Number.isFinite)}
function maxPrice(p){const values=numbers(p.price);return values.length?Math.max(...values):0}
function usdPrice(p){const value=maxPrice(p);return value?'US$'+Math.round(value/USD_RATE_DOP)+' aprox.':''}
function preferredTheme(){try{const value=localStorage.getItem(THEME_KEY);return ['light','dark','system'].includes(value)?value:'system'}catch{return 'system'}}
function applyTheme(value){const mode=['light','dark','system'].includes(value)?value:'system';if(mode==='system')document.documentElement.removeAttribute('data-theme');else document.documentElement.dataset.theme=mode;const control=$('#themeMode');if(control)control.value=mode;try{localStorage.setItem(THEME_KEY,mode)}catch{}}
function allNotes(p){return [...(p.notes_top||[]),...(p.notes_heart||[]),...(p.notes_base||[])]}
function whatsapp(p){const status=p.availability==='agotado'?'está agotado; quisiera saber cuándo vuelve':p.availability==='encargo'?'es por encargo; quisiera solicitarlo':'me interesa';return 'https://wa.me/18094333348?text='+encodeURIComponent('Hola Elite Scents RD, '+status+': '+p.name+' ('+p.size+', '+p.price+'). ¿Puedes ayudarme?')}
function validImage(url){return typeof url==='string'&&!/\/pages\/page-/i.test(url)&&(/^https:\/\//i.test(url)||/^\/img\/productos\/[0-9]{4,}-[a-z0-9-]+\.(jpe?g|png|webp)$/i.test(url))}
function thumbOf(url){return /^\/img\/productos\/[^/]+\.(jpe?g|png)$/i.test(url)?url.replace('/img/productos/','/img/productos/thumbs/').replace(/\.(jpe?g|png)$/i,'.webp'):url}
function catalogueVisual(p,className='photo'){const wrap=document.createElement('div');wrap.className=className;
if(validImage(p.image_url)){wrap.classList.add('custom');const img=document.createElement('img');img.src=thumbOf(p.image_url);img.alt='Frasco de '+p.name+(p.brand?' de '+p.brand:'');img.width=420;img.height=420;img.loading='lazy';img.decoding='async';wrap.append(img);return wrap}
wrap.classList.add('placeholder');wrap.setAttribute('role','img');wrap.setAttribute('aria-label','Foto próximamente de '+p.name);return wrap}
function favoriteButton(p){const button=document.createElement('button');button.type='button';button.className='favorite-button';const selected=favoriteIds.has(Number(p.id));button.textContent=selected?'♥':'♡';button.setAttribute('aria-label',(selected?'Quitar ':'Agregar ')+p.name+(selected?' de favoritos':' a favoritos'));button.setAttribute('aria-pressed',String(selected));button.addEventListener('click',e=>{e.stopPropagation();const id=Number(p.id);favoriteIds.has(id)?favoriteIds.delete(id):favoriteIds.add(id);saveFavorites();render()});return button}
function slugify(s){return String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/&/g,' y ').replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,70).replace(/-$/,'')}
function productPath(p){return '/perfumes/'+slugify(p.name)+'-'+p.id+'.html'}
function openFromHash(){const m=/^#(producto|avisame)-(\d+)$/.exec(location.hash);if(!m)return;const p=products.find(x=>Number(x.id)===Number(m[2]));const dialog=$('#productDialog');if(p&&dialog&&!dialog.open)openProduct(p,{notify:m[1]==='avisame'})}
function offerBadge(p){if(!p.original_price)return [];const b=document.createElement('span');b.className='offer-badge';b.textContent='OFERTA'+(p.offer_label?' · '+p.offer_label:'');return [b]}
function inspiredLine(p){if(!p.inspired_by)return [];const line=document.createElement('p');line.className='inspired';const ref=document.createElement('span');ref.textContent=p.inspired_by;line.append('Inspirado en ',ref);return [line]}
function notifyButton(p){if(p.availability!=='agotado'&&p.availability!=='encargo')return [];const b=document.createElement('button');b.type='button';b.className='notify-link';b.textContent='🔔 Avísame cuando llegue';b.addEventListener('click',()=>openProduct(p,{notify:true}));return [b]}
function card(p,inShelf){const item=document.createElement('article');item.className='perfume';if(!inShelf)item.id='producto-'+p.id;item.dataset.productId=p.id;const visual=catalogueVisual(p);visual.append(favoriteButton(p));const status=p.availability in statusLabel?p.availability:'disponible';const badge=document.createElement('span');badge.className='stock stock-'+status;badge.textContent=statusLabel[status];const meta=document.createElement('div');meta.className='meta';const brand=document.createElement('span');brand.textContent=p.brand||genderLabel[p.gender]||'Perfume';const volume=document.createElement('span');volume.textContent=p.size||'';meta.append(brand,volume);const title=document.createElement('h3');const titleLink=document.createElement('a');titleLink.href=productPath(p);titleLink.textContent=p.name;title.append(titleLink);const note=document.createElement('div');note.className='size';note.textContent=allNotes(p).slice(0,3).join(' · ')||(genderLabel[p.gender]||'Unisex');const price=document.createElement('div');price.className='price'+(p.original_price?' price-offer':'');const dop=document.createElement('strong');dop.textContent=(p.original_price?'Ahora ':'')+(p.price||'Precio a confirmar');const usd=document.createElement('small');usd.textContent=usdPrice(p);if(p.original_price){const was=document.createElement('small');was.className='price-was';const old=document.createElement('s');old.textContent=p.original_price;was.append('Antes ',old);price.append(was)}price.append(dop,usd);const actions=document.createElement('div');actions.className='card-actions';const detail=document.createElement('button');detail.type='button';detail.textContent='Ver detalles';detail.addEventListener('click',()=>openProduct(p));const wa=document.createElement('a');wa.href=whatsapp(p);wa.target='_blank';wa.rel='noopener noreferrer';wa.textContent=status==='agotado'?'Consultar reposición ↗':status==='encargo'?'Solicitar por encargo ↗':'WhatsApp ↗';actions.append(detail,wa);item.append(visual,badge,...offerBadge(p),meta,title,...inspiredLine(p),note,price,...notifyButton(p),actions);return item}
function priceMatches(p,value){const n=maxPrice(p);if(value==='under3000')return n<3000;if(value==='3000-4999')return n>=3000&&n<5000;if(value==='5000-6999')return n>=5000&&n<7000;if(value==='7000plus')return n>=7000;return true}
function matches(){const term=norm(q.value.trim()),brand=brandFilter.value,note=noteFilter.value,status=availabilityFilter.value;return products.filter(p=>{
const searchable=norm([p.name,p.brand,p.size,p.price,p.inspired_by,...allNotes(p)].join(' '));
return (!term||searchable.includes(term))&&(gender==='todos'||p.gender===gender)&&(brand==='all'||p.brand===brand)&&(note==='all'||allNotes(p).includes(note))&&(status==='all'||p.availability===status)&&priceMatches(p,priceFilter.value)&&specialMatches(p,specialFilter?.value||'all')&&(!onlyFavorites||favoriteIds.has(Number(p.id)))
})}
function specialMatches(p,value){if(value==='ofertas')return Boolean(p.original_price);if(value==='nuevos')return homeSections.nuevos.includes(Number(p.id));if(value==='vendidos')return homeSections.vendidos.includes(Number(p.id));return true}
function specialOrder(list){const value=specialFilter?.value;const ranking=value==='vendidos'?homeSections.vendidos:value==='nuevos'?homeSections.nuevos:null;return ranking?[...list].sort((a,b)=>ranking.indexOf(Number(a.id))-ranking.indexOf(Number(b.id))):list}
function render(){const result=specialOrder(matches()),fragment=document.createDocumentFragment();result.slice(0,visible).forEach(p=>fragment.append(card(p)));grid.replaceChildren(fragment);count.textContent=result.length+' '+(result.length===1?'fragancia':'fragancias');empty.hidden=result.length!==0;more.hidden=result.length<=visible;favoritesOnly.classList.toggle('active',onlyFavorites);favoritesOnly.textContent=onlyFavorites?'♥ Mis favoritos':'♡ Mis favoritos'}
function unique(values){return [...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es',{sensitivity:'base'}))}
function option(value,label=value){const o=document.createElement('option');o.value=value;o.textContent=label;return o}
function prepareFilters(){brandFilter.replaceChildren(brandFilter.options[0]);noteFilter.replaceChildren(noteFilter.options[0]);unique(products.map(p=>p.brand)).forEach(v=>brandFilter.append(option(v)));unique(products.flatMap(allNotes)).forEach(v=>noteFilter.append(option(v)))}
function showSuggestions(){const term=norm(q.value.trim());if(term.length<2){closeSuggestions();return}const found=products.filter(p=>norm(p.name+' '+p.brand+' '+(p.inspired_by||'')).includes(term)).slice(0,7);suggestions.replaceChildren();found.forEach((p,i)=>{const li=document.createElement('li');li.role='option';li.id='suggestion-'+i;li.textContent=p.name+(p.brand?' · '+p.brand:'')+(p.inspired_by&&!norm(p.name+' '+p.brand).includes(term)?' · inspirado en '+p.inspired_by:'');li.addEventListener('mousedown',e=>{e.preventDefault();chooseSuggestion(p.name)});suggestions.append(li)});suggestions.hidden=!found.length;q.setAttribute('aria-expanded',String(!!found.length));suggestionIndex=-1}
function closeSuggestions(){suggestions.hidden=true;suggestions.replaceChildren();q.setAttribute('aria-expanded','false');q.removeAttribute('aria-activedescendant');suggestionIndex=-1}
function chooseSuggestion(name){q.value=name;closeSuggestions();visible=24;render();$('#coleccion').scrollIntoView()}
function moveSuggestion(direction){const items=[...suggestions.children];if(!items.length)return;suggestionIndex=(suggestionIndex+direction+items.length)%items.length;items.forEach((el,i)=>el.classList.toggle('selected',i===suggestionIndex));q.setAttribute('aria-activedescendant',items[suggestionIndex].id)}
function fillText(id,values){$(id).textContent=values?.length?values.join(', '):'Información pendiente'}
function galleryUrls(p){return unique([p.image_url,...(p.gallery_urls||[])]).filter(validImage).slice(0,3)}
function openProduct(p,opts={}){const dialog=$('#productDialog'),main=$('#dialogMainImage'),gallery=$('#dialogGallery');if(dialog){dialog.dataset.productId=p.id;window.EliteStats?.track('perfume',{product_id:p.id})}{const insp=$('#dialogInspired');if(insp){insp.hidden=!p.inspired_by;insp.textContent=p.inspired_by?'Inspirado en '+p.inspired_by:''}}prepareNotify(p,opts.notify);$('#dialogBrand').textContent=p.brand||'Elite Scents RD';$('#dialogTitle').textContent=p.name;{const was=$('#dialogPriceWas');was.hidden=!p.original_price;was.replaceChildren();if(p.original_price){const old=document.createElement('s');old.textContent=p.original_price;was.append('Antes ',old)}}$('#dialogPrice').textContent=(p.original_price?'Ahora ':'')+(p.price||'Precio a confirmar');$('#dialogPriceUsd').textContent=usdPrice(p);$('#dialogSize').textContent=p.size||'Por confirmar';$('#dialogStatus').className='stock stock-'+p.availability;$('#dialogStatus').textContent=statusLabel[p.availability]||'Disponible';$('#dialogDescription').textContent=p.description||'Consulta por WhatsApp la disponibilidad, presentación y detalles de esta fragancia.';fillText('#dialogTop',p.notes_top);fillText('#dialogHeart',p.notes_heart);fillText('#dialogBase',p.notes_base);const wa=$('#dialogWhatsapp');wa.href=whatsapp(p);const add=$('#dialogAddCart');if(add){add.disabled=p.availability==='agotado';add.onclick=()=>addToCart(p)}gallery.replaceChildren();main.replaceChildren();const urls=galleryUrls(p);const webp=url=>url===p.image_url&&p.image_webp?p.image_webp:url;if(urls.length){const image=document.createElement('img');image.src=webp(urls[0]);image.alt='Frasco de '+p.name;image.loading='eager';main.append(image);urls.forEach((url,i)=>{const b=document.createElement('button');b.type='button';b.setAttribute('aria-label','Ver imagen '+(i+1)+' de '+p.name);const img=document.createElement('img');img.src=url;img.alt='Vista '+(i+1)+' del perfume '+p.name;img.loading='lazy';b.append(img);b.addEventListener('click',()=>{image.src=url;image.alt='Vista '+(i+1)+' del perfume '+p.name});gallery.append(b)})}else main.append(catalogueVisual(p,'dialog-catalogue-image'));if(!dialog.open)dialog.showModal();if(opts.notify){const box=$('#notifyBox');if(box&&!box.hidden){box.scrollIntoView({block:'center'});$('#notifyForm')?.elements.name.focus()}}}
function resetFilters(){q.value='';gender='todos';onlyFavorites=false;priceFilter.value=brandFilter.value=noteFilter.value=availabilityFilter.value='all';if(specialFilter)specialFilter.value='all';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter==='todos'));visible=24;closeSuggestions();render()}
function unavailable(){grid.setAttribute('aria-busy','false');empty.textContent='El catálogo no está disponible ahora. Escríbenos por WhatsApp para consultar un perfume.';if(grid.querySelector('.perfume[data-product-id]')){empty.hidden=true;catalogMessage('No pudimos actualizar el catálogo. Estos son algunos perfumes; consulta disponibilidad por WhatsApp.');count.textContent='';return}products=[];render();empty.hidden=false;count.textContent='Catálogo no disponible'}
function catalogMessage(message){const el=$('#catalogStatus');if(el)el.textContent=message}
// Promoción de la encuesta: aparece solo si está activa en el panel y muestra el monto actual del cupón.
async function surveyPromo(){const promo=$('#encuesta-promo'),base=String(cfg.url||'').replace(/\/$/,'');if(!promo||!key||!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(base))return;try{const res=await fetch(base+'/rest/v1/rpc/survey_info',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:'{}'});if(!res.ok)return;const info=await res.json();if(!info||info.enabled!==true)return;if(Number(info.amount)>0)document.querySelectorAll('[data-survey-amount]').forEach(el=>{el.textContent='RD$'+new Intl.NumberFormat('es-DO').format(Number(info.amount))});promo.hidden=false}catch{}}
// Asistente "Encuentra tu perfume": 4 preguntas cortas y una recomendación según las notas de cada perfume (la lógica está en aroma.js).
const finderDialog=$('#finderDialog'),Aroma=window.EliteAroma;
let finderStep=0,finderAnswers={};
function finderReset(){finderStep=0;finderAnswers={who:'',occasion:'',families:[],budget:''}}
function finderOpen(){finderReset();renderFinder();if(!finderDialog.open)finderDialog.showModal()}
function markFinderSelection(step){const chosen=step.multi?finderAnswers[step.id]:[finderAnswers[step.id]];$('#finderOptions').querySelectorAll('.finder-option').forEach(b=>{const on=chosen.includes(b.dataset.value);b.classList.toggle('selected',on);b.setAttribute('aria-pressed',String(on))});if(step.multi)$('#finderNext').disabled=!finderAnswers[step.id].length}
function chooseFinderOption(step,option){
 if(step.multi){let list=finderAnswers[step.id];if(option.exclusive)list=list.includes(option.value)?[]:[option.value];else{list=list.filter(v=>v!=='ninguno');list=list.includes(option.value)?list.filter(v=>v!==option.value):[...list,option.value].slice(-step.max)}finderAnswers[step.id]=list;markFinderSelection(step);return}
 finderAnswers[step.id]=option.value;finderStep++;renderFinder();
}
function renderFinder(){
 const steps=Aroma.STEPS;if(finderStep>=steps.length){renderFinderResults();return}
 const step=steps[finderStep];$('#finderQuestion').hidden=false;$('#finderResults').hidden=true;
 $('#finderStep').textContent='PASO '+(finderStep+1)+' DE '+steps.length;$('#finderTitle').textContent=step.title;$('#finderHelp').textContent=step.help||'';
 const box=$('#finderOptions');box.replaceChildren();
 step.options.forEach(option=>{const b=document.createElement('button');b.type='button';b.className='finder-option';b.dataset.value=option.value;const label=document.createElement('strong');label.textContent=option.label;b.append(label);if(option.hint){const hint=document.createElement('small');hint.textContent=option.hint;b.append(hint)}b.addEventListener('click',()=>chooseFinderOption(step,option));box.append(b)});
 markFinderSelection(step);$('#finderBack').hidden=finderStep===0;$('#finderNext').hidden=!step.multi;box.querySelector('button')?.focus();
}
function renderFinderResults(){
 $('#finderQuestion').hidden=true;$('#finderResults').hidden=false;$('#finderStep').textContent='TUS RECOMENDACIONES';$('#finderTitle').textContent='Estas opciones son para ti';
 const {items,total}=Aroma.recommend(products,finderAnswers,6),summary=Aroma.describeAnswers(finderAnswers);
 $('#finderSummary').textContent=items.length?(summary?'Buscaste un perfume '+summary+'. ':'')+'Mostramos '+items.length+' de '+total+' que coinciden, ordenados por afinidad con las notas de cada uno.':'No encontramos perfumes con esas condiciones.';
 $('#finderGrid').replaceChildren(...items.map(({product,reasons})=>{const article=card(product);if(reasons.length){const why=document.createElement('p');why.className='finder-reason';why.textContent='Coincide: '+reasons.slice(0,2).map(r=>r.label.toLowerCase()+' ('+r.notes.join(', ')+')').join(' · ');article.append(why)}return article}));
 const few=$('#finderFew');few.hidden=total>=3;few.textContent=total>=3?'':'Hay pocas coincidencias exactas. Prueba con otros gustos o un presupuesto mayor, o pídenos una recomendación por WhatsApp.';
 $('#finderWhatsapp').href='https://wa.me/18094333348?text='+encodeURIComponent('Hola Elite Scents RD, quiero una recomendación de perfume'+(summary?' '+summary:'')+'. ¿Me ayudas?');
 finderDialog.scrollTop=0;
}
if(finderDialog&&Aroma){
 document.addEventListener('click',e=>{if(e.target.closest('[data-open-finder]')&&products.length){e.preventDefault();finderOpen()}});
 $('#finderClose').addEventListener('click',()=>finderDialog.close());finderDialog.addEventListener('click',e=>{if(e.target===finderDialog)finderDialog.close()});
 $('#finderBack').addEventListener('click',()=>{if(finderStep>0){finderStep--;renderFinder()}});$('#finderNext').addEventListener('click',()=>{finderStep++;renderFinder()});
 $('#finderRestart').addEventListener('click',()=>{finderReset();renderFinder()});
 $('#finderCatalog').addEventListener('click',()=>{finderDialog.close();resetFilters();if(finderAnswers.who==='hombre'||finderAnswers.who==='mujer'){gender=finderAnswers.who;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===gender));render()}$('#coleccion').scrollIntoView()});
}
// «Lo más vendido», «En oferta» y «Nuevos»: filas horizontales con las mismas tarjetas del catálogo (máximo 12 por fila).
function offerPercent(p){const was=numbers(p.original_price),now=numbers(p.price);return was[0]&&now[0]?1-now[0]/was[0]:0}
function shelfItems(kind){const byId=new Map(products.map(p=>[Number(p.id),p]));if(kind==='ofertas')return products.filter(p=>p.original_price).sort((a,b)=>offerPercent(b)-offerPercent(a)).slice(0,12);return (homeSections[kind]||[]).map(id=>byId.get(id)).filter(Boolean).slice(0,12)}
function renderShelves(){const box=$('#destacados');if(!box)return;let shown=0;box.querySelectorAll('[data-shelf]').forEach(shelf=>{const kind=shelf.dataset.shelf,items=shelfItems(kind),min=kind==='vendidos'?4:3,row=shelf.querySelector('.shelf-row');shelf.hidden=items.length<min;if(shelf.hidden){row.replaceChildren();return}shown++;row.replaceChildren(...items.map(p=>{const c=card(p,true);c.setAttribute('role','listitem');return c}))});box.hidden=!shown}
function showShelf(kind){if(!specialFilter)return;resetFilters();specialFilter.value=kind;visible=24;render();$('#coleccion').scrollIntoView()}
document.querySelectorAll('[data-shelf-all]').forEach(b=>b.addEventListener('click',()=>showShelf(b.dataset.shelfAll)));
// «Avísame cuando llegue»: nombre y WhatsApp para perfumes agotados o por encargo (la base de datos valida y limita).
let notifyProduct=null;
function prepareNotify(p,focus){const box=$('#notifyBox'),form=$('#notifyForm'),st=$('#notifyStatus');if(!box||!form)return;notifyProduct=p;const show=p.availability==='agotado'||p.availability==='encargo';box.hidden=!show;st.textContent='';st.className='notify-status';form.hidden=false;const button=form.querySelector('button');if(button)button.disabled=false}
function notifyMessage(text,kind){const st=$('#notifyStatus');st.textContent=text;st.className='notify-status'+(kind?' '+kind:'')}
async function sendNotify(e){e.preventDefault();const form=e.currentTarget,p=notifyProduct;if(!p)return;const name=form.elements.name.value.trim(),phone=form.elements.phone.value.trim(),digits=phone.replace(/\D/g,'').replace(/^1(?=\d{10}$)/,'');
 if(String(form.elements.website?.value||'').trim()){notifyMessage('Listo: te escribiremos por WhatsApp cuando llegue.','success');form.hidden=true;return}
 if(name.length<2){notifyMessage('Escribe tu nombre.','error');form.elements.name.focus();return}
 if(!/^(809|829|849)\d{7}$/.test(digits)){notifyMessage('Escribe tu WhatsApp dominicano de 10 dígitos (809, 829 u 849).','error');form.elements.phone.focus();return}
 const base=String(cfg.url||'').replace(/\/$/,''),button=form.querySelector('button');if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(base)||!key){notifyMessage('No pudimos anotarte ahora. Escríbenos por WhatsApp al 809-433-3348.','error');return}
 button.disabled=true;notifyMessage('Anotando…');
 try{const res=await fetch(base+'/rest/v1/rpc/request_restock_alert',{method:'POST',headers:{apikey:key,'Content-Type':'application/json'},body:JSON.stringify({p_product_id:Number(p.id),p_name:name,p_phone:digits})});const data=await res.json().catch(()=>null);
  if(!res.ok||!data)throw new Error('HTTP '+res.status);
  if(data.ok){notifyMessage(data.message||'Listo: te escribiremos por WhatsApp cuando llegue.','success');form.hidden=true}else{notifyMessage(data.message||'Revisa tus datos.','error');button.disabled=false}
 }catch{notifyMessage('No pudimos anotarte ahora. Escríbenos por WhatsApp al 809-433-3348.','error');button.disabled=false}}
$('#notifyForm')?.addEventListener('submit',sendNotify);
document.addEventListener('click',e=>{const b=e.target.closest('#productGrid [data-open-product],#productGrid [data-notify-product],.shelf-row [data-open-product],.shelf-row [data-notify-product]');if(!b)return;const notify='notifyProduct' in b.dataset,id=Number(notify?b.dataset.notifyProduct:b.dataset.openProduct),p=products.find(x=>Number(x.id)===id);e.preventDefault();if(p)openProduct(p,{notify});else location.hash=(notify?'avisame-':'producto-')+id});
// Precios, disponibilidad y ofertas al día desde la base de datos (unos 3 KB). Si alguien agregó perfumes después de la
// última publicación, esos se piden completos. Sin /perfumes.json (por ejemplo sin conexión la primera vez) se pide todo.
const LIVE_FIELDS='id,price,original_price,offer_label,offer_ends_at,availability,sort_order';
const liveSignature=list=>list.map(p=>[p.id,p.price,p.original_price,p.offer_label,p.availability].join('|')).join(';');
async function load(){const base=String(cfg.url||'').replace(/\/$/,'');if(!/^https:\/\/[a-z0-9-]+\.supabase\.co$/i.test(base)||!key){if(!products.length)unavailable();return}const controller=new AbortController(),timer=setTimeout(()=>controller.abort(),8000);try{const known=preRenderedById.size>0,headers={apikey:key};let response=await fetch(API+'?select='+(known?LIVE_FIELDS:'*')+'&active=eq.true&order=sort_order.asc,id.asc&limit=1000',{headers,signal:controller.signal});if(known&&response.status===400)response=await fetch(API+'?select=*&active=eq.true&order=sort_order.asc,id.asc&limit=1000',{headers,signal:controller.signal});if(!response.ok)throw new Error('HTTP '+response.status);const fresh=await response.json();if(!Array.isArray(fresh)||!fresh.length)throw new Error('Catálogo vacío');const missing=known?fresh.map(r=>Number(r.id)).filter(id=>Number.isFinite(id)&&!preRenderedById.has(id)).slice(0,200):[],extra=new Map();if(missing.length){const more=await fetch(API+'?select=*&id=in.('+missing.join(',')+')',{headers,signal:controller.signal});if(more.ok)for(const p of await more.json())extra.set(Number(p.id),p)}const next=fresh.map(row=>{const saved=preRenderedById.get(Number(row.id));if(saved)return {...saved,...row,description:row.description||saved.description,image_url:validImage(row.image_url)?row.image_url:saved.image_url||null,image_webp:validImage(row.image_url)&&row.image_url!==saved.image_url?null:saved.image_webp,notes_top:row.notes_top?.length?row.notes_top:saved.notes_top,notes_heart:row.notes_heart?.length?row.notes_heart:saved.notes_heart,notes_base:row.notes_base?.length?row.notes_base:saved.notes_base,inspired_by:row.inspired_by||saved.inspired_by||null};const p=extra.get(Number(row.id))||row;return p.name?{...p,image_url:validImage(p.image_url)?p.image_url:null}:null}).filter(Boolean);const grew=next.length!==products.length,changed=grew||liveSignature(next)!==liveSignature(products);products=next;if(grew)prepareFilters();if(changed){render();renderShelves()}updateFavoriteSummary();grid.setAttribute('aria-busy','false');catalogMessage('')}catch{if(products.length){grid.setAttribute('aria-busy','false');catalogMessage('Mostrando la última versión guardada del catálogo. Puedes consultar disponibilidad por WhatsApp.')}else unavailable()}finally{clearTimeout(timer)}}
// Búsqueda desde otra página (por ejemplo la 404): /?q=texto llena el buscador y muestra los resultados.
let queryApplied=false;function applyQueryParam(){if(queryApplied||!products.length)return;queryApplied=true;const term=(new URLSearchParams(location.search).get('q')||'').trim().slice(0,60);if(!term)return;q.value=term;visible=24;render();trackSearch();$('#coleccion')?.scrollIntoView()}
async function start(){const src=catalogSource();if(src){try{const res=await fetch(src);if(res.ok){const list=await res.json();if(Array.isArray(list)&&list.length){products=list;preRenderedById=new Map(list.map(p=>[Number(p.id),p]));prepareFilters();render();renderShelves();updateFavoriteSummary();grid.setAttribute('aria-busy','false');applyQueryParam();openFromHash()}}}catch{}}await load();applyQueryParam();openFromHash()}
let searchTimer=0,lastSearch='';function trackSearch(){const term=q.value.trim();if(term.length<3||norm(term)===lastSearch)return;lastSearch=norm(term);window.EliteStats?.track(matches().length?'busqueda':'sin_resultado',{term})}
q.addEventListener('input',()=>{visible=24;showSuggestions();render();clearTimeout(searchTimer);searchTimer=setTimeout(trackSearch,1500)});q.addEventListener('keydown',e=>{if(e.key==='ArrowDown'){e.preventDefault();moveSuggestion(1)}else if(e.key==='ArrowUp'){e.preventDefault();moveSuggestion(-1)}else if(e.key==='Enter'&&suggestionIndex>=0){e.preventDefault();chooseSuggestion(suggestions.children[suggestionIndex].textContent.split(' · ')[0])}else if(e.key==='Escape')closeSuggestions()});q.addEventListener('blur',()=>setTimeout(closeSuggestions,120));
[priceFilter,brandFilter,noteFilter,availabilityFilter,specialFilter].filter(Boolean).forEach(el=>el.addEventListener('change',()=>{visible=24;render()}));
document.querySelectorAll('[data-filter]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-filter]').forEach(b=>b.classList.remove('active'));button.classList.add('active');gender=button.dataset.filter;visible=24;render()}));
favoritesOnly.addEventListener('click',()=>{onlyFavorites=!onlyFavorites;visible=24;render()});$('#showFavorites')?.addEventListener('click',()=>{onlyFavorites=true;visible=24;render();$('#coleccion').scrollIntoView()});$('#clearFilters').addEventListener('click',resetFilters);more.addEventListener('click',()=>{visible+=24;render()});$('#dialogClose').addEventListener('click',()=>$('#productDialog').close());$('#productDialog').addEventListener('click',e=>{if(e.target===$('#productDialog'))$('#productDialog').close()});applyTheme(preferredTheme());$('#themeMode')?.addEventListener('change',e=>applyTheme(e.target.value));$('#year').textContent=new Date().getFullYear();updateCartCount();updateFavoriteSummary();start();surveyPromo()
})();
